package com.ly.common.eventBus;

/**
 * Created by ly on 2017/8/31 17:06.
 */
public enum EventBusFlag {
    ACTION_PAY_RESULT,
    ACTION_PAY_SUCCESS,
    ACTION_PAY_FAIL_SELF_ORDER_SAME_DATE,
    ACTION_ACTIVE_SUCCESS,
    ACTION_IDENTITY_SUCCESS,
    ACTION_SHARE_CARD_SUCCESS,
    ACTION_OPEN_VIP_SUCCESS,
    ACTION_TICKET_SUCCESS,
    ACTION_HOME_VIP,
    ACTION_HOME_SCENIC,
    ACTION_ACCOUNT_DEL,
    ACTION_FINISH_WEB_PAGE,
    ACTION_LOGIN_SUCCESS
}
